version: "3.3"
services:
  mysql:
    image: "mysql"
    hostname: "mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
    volumes:
      - ${PWD}/mysql/:/docker-entrypoint-initdb.d/